repos:
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.2.0"
  hooks:
    - id: pyproject-fmt
# Ruff must be run before Black, so Black can reformat fixes made by Ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.292
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: "23.9.1"
  hooks:
    - id: black
      args: [--preview]
